# Generated by go2rpm 1.19.0
%bcond check 1
%bcond bootstrap 0

%if %{with bootstrap}
%global debug_package %{nil}
%endif

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/smoliicek/pufferstarter-cli
%global goipath         github.com/smoliicek/pufferstarter-cli
Version:                4.0.1

%gometa -f

%global common_description %{expand:
CLI tool for managing your PufferPanel servers. List, inspect, and control
power state, all from your terminal!}

%global golicenses      LICENSE LICENSES
%global godocs          docs README.md

Name:           pufferstarter-cli
Release:        %autorelease
Summary:        CLI tool for managing your PufferPanel servers. List, inspect, and control power state, all from your terminal

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%if %{without bootstrap}
%build
%gobuild -o %{gobuilddir}/bin/pufferstarter-cli %{goipath}
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{without bootstrap}
%if %{with check}
%check
%gocheck
%endif
%endif

%if %{without bootstrap}
%files
%license LICENSE LICENSES
%doc docs README.md
%{_bindir}/pufferstarter-cli
%endif

%gopkgfiles

%changelog
%autochangelog
